### ISSUE TITLE
Downloaded bytes did not match Content-Length 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [oobabooga/one-click-installers#113]
download never completes. tries to redownload the files again and again

```
What is your GPU

A) NVIDIA
B) AMD (Linux/MacOS only. Requires ROCm SDK 5.4.2/5.4.3 on Linux)
C) Apple M Series
D) None (I want to run in CPU mode)

Input> A
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.7.2

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.2



## Package Plan ##

  environment location: C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env

  added / updated specs:
    - cuda
    - git
    - ninja


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cuda-cccl-11.7.58          |                0         1.2 MB  nvidia/label/cuda-11.7.0
    cuda-command-line-tools-11.7.0|                0           1 KB  nvidia/label/cuda-11.7.0
    cuda-cudart-dev-11.7.60    |                0         695 KB  nvidia/label/cuda-11.7.0
    cuda-cupti-11.7.50         |                0        10.2 MB  nvidia/label/cuda-11.7.0
    cuda-libraries-dev-11.7.0  |                0           1 KB  nvidia/label/cuda-11.7.0
    cuda-memcheck-11.7.50      |                0         183 KB  nvidia/label/cuda-11.7.0
    cuda-nsight-compute-11.7.0 |                0           1 KB  nvidia/label/cuda-11.7.0
    cuda-nvcc-11.7.64          |                0        44.2 MB  nvidia/label/cuda-11.7.0
    cuda-nvprune-11.7.50       |                0         152 KB  nvidia/label/cuda-11.7.0
    cuda-nvrtc-dev-11.7.50     |                0        14.3 MB  nvidia/label/cuda-11.7.0
    cuda-nvtx-11.7.50          |                0          43 KB  nvidia/label/cuda-11.7.0
    cuda-sanitizer-api-11.7.50 |                0        12.6 MB  nvidia/label/cuda-11.7.0
    cuda-toolkit-11.7.0        |                0           1 KB  nvidia/label/cuda-11.7.0
    cuda-visual-tools-11.7.0   |                0           1 KB  nvidia/label/cuda-11.7.0
    git-2.40.1                 |       haa95532_1        69.2 MB
    libcublas-dev-11.10.1.25   |                0       286.3 MB  nvidia/label/cuda-11.7.0
    libcufft-10.7.2.50         |                0           6 KB  nvidia/label/cuda-11.7.0
    libcusolver-11.3.5.50      |                0          29 KB  nvidia/label/cuda-11.7.0
    libcusparse-11.7.3.50      |                0          13 KB  nvidia/label/cuda-11.7.0
    libcusparse-dev-11.7.3.50  |                0       147.6 MB  nvidia/label/cuda-11.7.0
    libnpp-dev-11.7.3.21       |                0       114.3 MB  nvidia/label/cuda-11.7.0
    libnvjpeg-11.7.2.34        |                0           4 KB  nvidia/label/cuda-11.7.0
    libnvjpeg-dev-11.7.2.34    |                0         1.8 MB  nvidia/label/cuda-11.7.0
    ------------------------------------------------------------
                                           Total:       702.9 MB

The following NEW packages will be INSTALLED:

  cuda               nvidia/label/cuda-11.7.0/win-64::cuda-11.7.0-0
  cuda-cccl          nvidia/label/cuda-11.7.0/win-64::cuda-cccl-11.7.58-0
  cuda-command-line~ nvidia/label/cuda-11.7.0/win-64::cuda-command-line-tools-11.7.0-0
  cuda-compiler      nvidia/label/cuda-11.7.0/win-64::cuda-compiler-11.7.0-0
  cuda-cudart        nvidia/label/cuda-11.7.0/win-64::cuda-cudart-11.7.60-0
  cuda-cudart-dev    nvidia/label/cuda-11.7.0/win-64::cuda-cudart-dev-11.7.60-0
  cuda-cuobjdump     nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0
  cuda-cupti         nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0
  cuda-cuxxfilt      nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0
  cuda-demo-suite    nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0
  cuda-documentation nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0
  cuda-libraries     nvidia/label/cuda-11.7.0/win-64::cuda-libraries-11.7.0-0
  cuda-libraries-dev nvidia/label/cuda-11.7.0/win-64::cuda-libraries-dev-11.7.0-0
  cuda-memcheck      nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0
  cuda-nsight-compu~ nvidia/label/cuda-11.7.0/win-64::cuda-nsight-compute-11.7.0-0
  cuda-nvcc          nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0
  cuda-nvdisasm      nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0
  cuda-nvml-dev      nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0
  cuda-nvprof        nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0
  cuda-nvprune       nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0
  cuda-nvrtc         nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-11.7.50-0
  cuda-nvrtc-dev     nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-dev-11.7.50-0
  cuda-nvtx          nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0
  cuda-nvvp          nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  cuda-runtime       nvidia/label/cuda-11.7.0/win-64::cuda-runtime-11.7.0-0
  cuda-sanitizer-api nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0
  cuda-toolkit       nvidia/label/cuda-11.7.0/win-64::cuda-toolkit-11.7.0-0
  cuda-tools         nvidia/label/cuda-11.7.0/win-64::cuda-tools-11.7.0-0
  cuda-visual-tools  nvidia/label/cuda-11.7.0/win-64::cuda-visual-tools-11.7.0-0
  git                pkgs/main/win-64::git-2.40.1-haa95532_1
  libcublas          nvidia/label/cuda-11.7.0/win-64::libcublas-11.10.1.25-0
  libcublas-dev      nvidia/label/cuda-11.7.0/win-64::libcublas-dev-11.10.1.25-0
  libcufft           nvidia/label/cuda-11.7.0/win-64::libcufft-10.7.2.50-0
  libcufft-dev       nvidia/label/cuda-11.7.0/win-64::libcufft-dev-10.7.2.50-0
  libcurand          nvidia/label/cuda-11.7.0/win-64::libcurand-10.2.10.50-0
  libcurand-dev      nvidia/label/cuda-11.7.0/win-64::libcurand-dev-10.2.10.50-0
  libcusolver        nvidia/label/cuda-11.7.0/win-64::libcusolver-11.3.5.50-0
  libcusolver-dev    nvidia/label/cuda-11.7.0/win-64::libcusolver-dev-11.3.5.50-0
  libcusparse        nvidia/label/cuda-11.7.0/win-64::libcusparse-11.7.3.50-0
  libcusparse-dev    nvidia/label/cuda-11.7.0/win-64::libcusparse-dev-11.7.3.50-0
  libnpp             nvidia/label/cuda-11.7.0/win-64::libnpp-11.7.3.21-0
  libnpp-dev         nvidia/label/cuda-11.7.0/win-64::libnpp-dev-11.7.3.21-0
  libnvjpeg          nvidia/label/cuda-11.7.0/win-64::libnvjpeg-11.7.2.34-0
  libnvjpeg-dev      nvidia/label/cuda-11.7.0/win-64::libnvjpeg-dev-11.7.2.34-0
  ninja              pkgs/main/win-64::ninja-1.10.2-haa95532_5
  ninja-base         pkgs/main/win-64::ninja-base-1.10.2-h6d14046_5
  nsight-compute     nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0



Downloading and Extracting Packages


CondaError: Downloaded bytes did not match Content-Length
  url: https://repo.anaconda.com/pkgs/main/win-64/git-2.40.1-haa95532_1.conda
  target_path: C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\conda\pkgs\git-2.40.1-haa95532_1.conda
  Content-Length: 72562082
  downloaded bytes: 40565127

CancelledError()
CancelledError()
CancelledError()
CancelledError()
CancelledError()
CancelledError()

Command '"C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env" >nul && conda install -y -k cuda ninja git -c nvidia/label/cuda-11.7.0 -c nvidia && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117' failed with exit status code '1'. Exiting...
Press any key to continue . . .
```

running:  `conda update -n base -c defaults conda`
seeing if this resolves

```
Traceback (most recent call last):
  File "C:\Users\Tom_N\Desktop\text-generation-webui\webui.py", line 295, in <module>
    update_dependencies()
  File "C:\Users\Tom_N\Desktop\text-generation-webui\webui.py", line 120, in update_dependencies
    os.chdir("text-generation-webui")
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'text-generation-webui'

Done!
Press any key to continue . . .
```
nope

try and rerun instller: 

What is your GPU

A) NVIDIA
B) AMD (Linux/MacOS only. Requires ROCm SDK 5.4.2/5.4.3 on Linux)
C) Apple M Series
D) None (I want to run in CPU mode)

Input> A
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env

  added / updated specs:
    - cuda
    - git
    - ninja

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cuda-cccl-11.7.58          |                0         1.2 MB  nvidia/label/cuda-11.7.0
    cuda-cupti-11.7.50         |                0        10.2 MB  nvidia/label/cuda-11.7.0
    cuda-nvcc-11.7.64          |                0        44.2 MB  nvidia/label/cuda-11.7.0
    cuda-nvprune-11.7.50       |                0         152 KB  nvidia/label/cuda-11.7.0
    cuda-sanitizer-api-11.7.50 |                0        12.6 MB  nvidia/label/cuda-11.7.0
    git-2.40.1                 |       haa95532_1        69.2 MB
    libcusolver-11.3.5.50      |                0          29 KB  nvidia/label/cuda-11.7.0
    ------------------------------------------------------------
                                           Total:       137.5 MB

The following NEW packages will be INSTALLED:

```
  cuda               nvidia/label/cuda-11.7.0/win-64::cuda-11.7.0-0
  cuda-cccl          nvidia/label/cuda-11.7.0/win-64::cuda-cccl-11.7.58-0
  cuda-command-line~ nvidia/label/cuda-11.7.0/win-64::cuda-command-line-tools-11.7.0-0
  cuda-compiler      nvidia/label/cuda-11.7.0/win-64::cuda-compiler-11.7.0-0
  cuda-cudart        nvidia/label/cuda-11.7.0/win-64::cuda-cudart-11.7.60-0
  cuda-cudart-dev    nvidia/label/cuda-11.7.0/win-64::cuda-cudart-dev-11.7.60-0
  cuda-cuobjdump     nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0
  cuda-cupti         nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0
  cuda-cuxxfilt      nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0
  cuda-demo-suite    nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0
  cuda-documentation nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0
  cuda-libraries     nvidia/label/cuda-11.7.0/win-64::cuda-libraries-11.7.0-0
  cuda-libraries-dev nvidia/label/cuda-11.7.0/win-64::cuda-libraries-dev-11.7.0-0
  cuda-memcheck      nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0
  cuda-nsight-compu~ nvidia/label/cuda-11.7.0/win-64::cuda-nsight-compute-11.7.0-0
  cuda-nvcc          nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0
  cuda-nvdisasm      nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0
  cuda-nvml-dev      nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0
  cuda-nvprof        nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0
  cuda-nvprune       nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0
  cuda-nvrtc         nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-11.7.50-0
  cuda-nvrtc-dev     nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-dev-11.7.50-0
  cuda-nvtx          nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0
  cuda-nvvp          nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  cuda-runtime       nvidia/label/cuda-11.7.0/win-64::cuda-runtime-11.7.0-0
  cuda-sanitizer-api nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0
  cuda-toolkit       nvidia/label/cuda-11.7.0/win-64::cuda-toolkit-11.7.0-0
  cuda-tools         nvidia/label/cuda-11.7.0/win-64::cuda-tools-11.7.0-0
  cuda-visual-tools  nvidia/label/cuda-11.7.0/win-64::cuda-visual-tools-11.7.0-0
  git                pkgs/main/win-64::git-2.40.1-haa95532_1
  libcublas          nvidia/label/cuda-11.7.0/win-64::libcublas-11.10.1.25-0
  libcublas-dev      nvidia/label/cuda-11.7.0/win-64::libcublas-dev-11.10.1.25-0
  libcufft           nvidia/label/cuda-11.7.0/win-64::libcufft-10.7.2.50-0
  libcufft-dev       nvidia/label/cuda-11.7.0/win-64::libcufft-dev-10.7.2.50-0
  libcurand          nvidia/label/cuda-11.7.0/win-64::libcurand-10.2.10.50-0
  libcurand-dev      nvidia/label/cuda-11.7.0/win-64::libcurand-dev-10.2.10.50-0
  libcusolver        nvidia/label/cuda-11.7.0/win-64::libcusolver-11.3.5.50-0
  libcusolver-dev    nvidia/label/cuda-11.7.0/win-64::libcusolver-dev-11.3.5.50-0
  libcusparse        nvidia/label/cuda-11.7.0/win-64::libcusparse-11.7.3.50-0
  libcusparse-dev    nvidia/label/cuda-11.7.0/win-64::libcusparse-dev-11.7.3.50-0
  libnpp             nvidia/label/cuda-11.7.0/win-64::libnpp-11.7.3.21-0
  libnpp-dev         nvidia/label/cuda-11.7.0/win-64::libnpp-dev-11.7.3.21-0
  libnvjpeg          nvidia/label/cuda-11.7.0/win-64::libnvjpeg-11.7.2.34-0
  libnvjpeg-dev      nvidia/label/cuda-11.7.0/win-64::libnvjpeg-dev-11.7.2.34-0
  ninja              pkgs/main/win-64::ninja-1.10.2-haa95532_5
  ninja-base         pkgs/main/win-64::ninja-base-1.10.2-h6d14046_5
  nsight-compute     nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0



Downloading and Extracting Packages
cuda-nvcc-11.7.64    | 44.2 MB   | ###6                                                                         |   5%
cuda-cccl-11.7.58    | 1.2 MB    | ############################################################################ | 100%
git-2.40.1           | 69.2 MB   | #########4                                                                   |  12%
cuda-nvprune-11.7.50 | 152 KB    | ############################################################################ | 100%
libcusolver-11.3.5.5 | 29 KB     | ############################################################################ | 100%
cuda-sanitizer-api-1 | 12.6 MB   | ############9                                                                |  17%

Preparing transaction: done
Verifying transaction: failed

SafetyError: The package for libcusparse-dev located at C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\conda\pkgs\libcusparse-dev-11.7.3.50-0
appears to be corrupted. The path 'bin/cusparse64_11.dll'
has an incorrect size.
  reported size: 232169472 bytes
  actual size: 167362560 bytes

CondaVerificationError: The package for libcusparse-dev located at C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\conda\pkgs\libcusparse-dev-11.7.3.50-0
appears to be corrupted. The path 'src/cusparse_fortran.c'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/win-64::git-2.40.1-haa95532_1, defaults/win-64::git-2.40.1-haa95532_1
  path: 'menu/menu-windows.json'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'license'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'build_env_setup.bat'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'conda_build.bat'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0, nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0, nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
  path: 'metadata_conda_debug.yaml'



Command '"C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\conda\condabin\conda.bat" activate "C:\Users\Tom_N\Desktop\text-generation-webui\installer_files\env" >nul && conda install -y -k cuda ninja git -c nvidia/label/cuda-11.7.0 -c nvidia && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117' failed with exit status code '1'. Exiting...
Press any key to continue . . .
```

rinses and repeat:

`conda clean --all
`

**Comment by jllllll** [comment]
Edit `start_windows.bat` and change:
```
set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe
```
To:
```
set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Windows-x86_64.exe
```
Does this fix your issue?
