### ISSUE TITLE
Not loading Pygmalion 7B under Oobabooga,  Error message RuntimeError: Internal: unk is not defined.

### ISSUE THREAD

**Issue by HolgerBr65** [oobabooga/one-click-installers#118]
Hello,
I downloaded the TheBloke_Pygmalion-7B-SuperHOT-8K-GPTQ file but can't load it.

Windows 11 PC with Nvidia RTX 4080 with 16 GB VRAM

Here is the error-message:
2023-08-04 15:11:00 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 68, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 86, in load_model
    tokenizer = load_tokenizer(model_name, model)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\text-generation-webui\modules\models.py", line 103, in load_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 144, in __init__
    self.sp_model.Load(vocab_file)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece\__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "C:\Users\User\Desktop\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\sentencepiece\__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: unk is not defined.

I am a Tier1 User. So, I can't find out, what to do here. Can someone help me?

Thanks

**Comment by oobabooga** [comment]
Wrong repository

**Comment by HolgerBr65** [comment]
Thank you for this hint. As I am a simple Tier1 user, how can I solve this without coding? Thank you
