### ISSUE TITLE
Cannot install/download Torch

### ISSUE THREAD

**Issue by ceria117** [oobabooga/one-click-installers#128]
I am getting this error every time I try to install using the installer.
It seems to either be related to torch or to my cuda install
Error occurs every time when : Collecting torch==2.0.1+cu117
Edit: it only takes about 10 seconds before it times out every time

I have tried: 
-Reinstalling every version of python on my computer
-Deleting pip and python from appdata (Local and Roaming) and a few other places that I found files pertaining to python
-Deleting the entire Ooba file and redownloading

Current PC Specs:
-OS: Windows 11
-RTX 4060ti 16gb
-Intel i9 9900k
-32gb ddr4

I have python 3.10.6 installed

-------------------------------------------
LOG:

    Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe to D:\AI\Oobabooga-NEW\installer_files\miniconda_installer.exe
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 53.8M  100 53.8M    0     0  1511k      0  0:00:36  0:00:36 --:--:-- 6950k
    Installing Miniconda to D:\AI\Oobabooga-NEW\installer_files\conda
    Miniconda version:
    conda 22.11.1
    Packages to install:
    Collecting package metadata (current_repodata.json): done
    Solving environment: done
    
    ## Package Plan ##
    
      environment location: D:\AI\Oobabooga-NEW\installer_files\env
    
      added / updated specs:
        - python=3.10
    
    
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        ca-certificates-2023.08.22 |       haa95532_0         123 KB
        libffi-3.4.4               |       hd77b12b_0         113 KB
        openssl-3.0.10             |       h2bbff1b_2         7.4 MB
        pip-23.2.1                 |  py310haa95532_0         2.8 MB
        python-3.10.12             |       he1021f5_0        15.8 MB
        setuptools-68.0.0          |  py310haa95532_0         934 KB
        sqlite-3.41.2              |       h2bbff1b_0         894 KB
        xz-5.4.2                   |       h8cc25b3_0         592 KB
        ------------------------------------------------------------
                                               Total:        28.6 MB
    
    The following NEW packages will be INSTALLED:
    
      bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0
      ca-certificates    pkgs/main/win-64::ca-certificates-2023.08.22-haa95532_0
      libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0
      openssl            pkgs/main/win-64::openssl-3.0.10-h2bbff1b_2
      pip                pkgs/main/win-64::pip-23.2.1-py310haa95532_0
      python             pkgs/main/win-64::python-3.10.12-he1021f5_0
      setuptools         pkgs/main/win-64::setuptools-68.0.0-py310haa95532_0
      sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0
      tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0
      tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
      vc                 pkgs/main/win-64::vc-14.2-h21ff451_1
      vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2
      wheel              pkgs/main/win-64::wheel-0.38.4-py310haa95532_0
      xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0
      zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0
    
    
    
    Downloading and Extracting Packages
    pip-23.2.1           | 2.8 MB    | ############################################################################ | 100%
    openssl-3.0.10       | 7.4 MB    | ############################################################################ | 100%
    libffi-3.4.4         | 113 KB    | ############################################################################ | 100%
    sqlite-3.41.2        | 894 KB    | ############################################################################ | 100%
    ca-certificates-2023 | 123 KB    | ############################################################################ | 100%
    python-3.10.12       | 15.8 MB   | ############################################################5                |  80%
    setuptools-68.0.0    | 934 KB    | ############################################################################ | 100%
    
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    #
    # To activate this environment, use
    #
    #     $ conda activate D:\AI\Oobabooga-NEW\installer_files\env
    #
    # To deactivate an active environment, use
    #
    #     $ conda deactivate
    
    What is your GPU
    
    A) NVIDIA
    B) AMD (Linux/MacOS only. Requires ROCm SDK 5.4.2/5.4.3 on Linux)
    C) Apple M Series
    D) None (I want to run models in CPU mode)
    
    Input> a
    Collecting package metadata (current_repodata.json): done
    Solving environment: done
    
    
    ==> WARNING: A newer version of conda exists. <==
      current version: 23.3.1
      latest version: 23.7.3
    
    Please update conda by running
    
        $ conda update -n base -c defaults conda
    
    Or to minimize the number of packages updated during conda update use
    
         conda install conda=23.7.3
    
    
    
    ## Package Plan ##
    
      environment location: D:\AI\Oobabooga-NEW\installer_files\env
    
      added / updated specs:
        - cuda
        - git
        - ninja
    
    
    The following packages will be downloaded:
    
        package                    |            build
        ---------------------------|-----------------
        cuda-11.7.0                |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-cccl-11.7.58          |                0         1.2 MB  nvidia/label/cuda-11.7.0
        cuda-command-line-tools-11.7.0|                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-compiler-11.7.0       |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-cudart-11.7.60        |                0         1.4 MB  nvidia/label/cuda-11.7.0
        cuda-cudart-dev-11.7.60    |                0         695 KB  nvidia/label/cuda-11.7.0
        cuda-cuobjdump-11.7.50     |                0         2.5 MB  nvidia/label/cuda-11.7.0
        cuda-cupti-11.7.50         |                0        10.2 MB  nvidia/label/cuda-11.7.0
        cuda-cuxxfilt-11.7.50      |                0         165 KB  nvidia/label/cuda-11.7.0
        cuda-demo-suite-11.7.50    |                0         4.6 MB  nvidia/label/cuda-11.7.0
        cuda-documentation-11.7.50 |                0          91 KB  nvidia/label/cuda-11.7.0
        cuda-libraries-11.7.0      |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-libraries-dev-11.7.0  |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-memcheck-11.7.50      |                0         183 KB  nvidia/label/cuda-11.7.0
        cuda-nsight-compute-11.7.0 |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-nvcc-11.7.64          |                0        44.2 MB  nvidia/label/cuda-11.7.0
        cuda-nvdisasm-11.7.50      |                0        31.6 MB  nvidia/label/cuda-11.7.0
        cuda-nvml-dev-11.7.50      |                0          85 KB  nvidia/label/cuda-11.7.0
        cuda-nvprof-11.7.50        |                0         1.5 MB  nvidia/label/cuda-11.7.0
        cuda-nvprune-11.7.50       |                0         152 KB  nvidia/label/cuda-11.7.0
        cuda-nvrtc-11.7.50         |                0        71.9 MB  nvidia/label/cuda-11.7.0
        cuda-nvrtc-dev-11.7.50     |                0        14.3 MB  nvidia/label/cuda-11.7.0
        cuda-nvtx-11.7.50          |                0          43 KB  nvidia/label/cuda-11.7.0
        cuda-nvvp-11.7.50          |                0       113.6 MB  nvidia/label/cuda-11.7.0
        cuda-runtime-11.7.0        |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-sanitizer-api-11.7.50 |                0        12.6 MB  nvidia/label/cuda-11.7.0
        cuda-toolkit-11.7.0        |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-tools-11.7.0          |                0           1 KB  nvidia/label/cuda-11.7.0
        cuda-visual-tools-11.7.0   |                0           1 KB  nvidia/label/cuda-11.7.0
        git-2.40.1                 |       haa95532_1        69.2 MB
        libcublas-11.10.1.25       |                0          24 KB  nvidia/label/cuda-11.7.0
        libcublas-dev-11.10.1.25   |                0       286.3 MB  nvidia/label/cuda-11.7.0
        libcufft-10.7.2.50         |                0           6 KB  nvidia/label/cuda-11.7.0
        libcufft-dev-10.7.2.50     |                0       249.8 MB  nvidia/label/cuda-11.7.0
        libcurand-10.2.10.50       |                0           3 KB  nvidia/label/cuda-11.7.0
        libcurand-dev-10.2.10.50   |                0        49.1 MB  nvidia/label/cuda-11.7.0
        libcusolver-11.3.5.50      |                0          29 KB  nvidia/label/cuda-11.7.0
        libcusolver-dev-11.3.5.50  |                0        86.6 MB  nvidia/label/cuda-11.7.0
        libcusparse-11.7.3.50      |                0          13 KB  nvidia/label/cuda-11.7.0
        libcusparse-dev-11.7.3.50  |                0       147.6 MB  nvidia/label/cuda-11.7.0
        libnpp-11.7.3.21           |                0         286 KB  nvidia/label/cuda-11.7.0
        libnpp-dev-11.7.3.21       |                0       114.3 MB  nvidia/label/cuda-11.7.0
        libnvjpeg-11.7.2.34        |                0           4 KB  nvidia/label/cuda-11.7.0
        libnvjpeg-dev-11.7.2.34    |                0         1.8 MB  nvidia/label/cuda-11.7.0
        ninja-1.10.2               |       haa95532_5          14 KB
        ninja-base-1.10.2          |       h6d14046_5         255 KB
        nsight-compute-2022.2.0.13 |                0       336.2 MB  nvidia/label/cuda-11.7.0
        ------------------------------------------------------------
                                               Total:        1.61 GB
    
    The following NEW packages will be INSTALLED:
    
      cuda               nvidia/label/cuda-11.7.0/win-64::cuda-11.7.0-0
      cuda-cccl          nvidia/label/cuda-11.7.0/win-64::cuda-cccl-11.7.58-0
      cuda-command-line~ nvidia/label/cuda-11.7.0/win-64::cuda-command-line-tools-11.7.0-0
      cuda-compiler      nvidia/label/cuda-11.7.0/win-64::cuda-compiler-11.7.0-0
      cuda-cudart        nvidia/label/cuda-11.7.0/win-64::cuda-cudart-11.7.60-0
      cuda-cudart-dev    nvidia/label/cuda-11.7.0/win-64::cuda-cudart-dev-11.7.60-0
      cuda-cuobjdump     nvidia/label/cuda-11.7.0/win-64::cuda-cuobjdump-11.7.50-0
      cuda-cupti         nvidia/label/cuda-11.7.0/win-64::cuda-cupti-11.7.50-0
      cuda-cuxxfilt      nvidia/label/cuda-11.7.0/win-64::cuda-cuxxfilt-11.7.50-0
      cuda-demo-suite    nvidia/label/cuda-11.7.0/win-64::cuda-demo-suite-11.7.50-0
      cuda-documentation nvidia/label/cuda-11.7.0/win-64::cuda-documentation-11.7.50-0
      cuda-libraries     nvidia/label/cuda-11.7.0/win-64::cuda-libraries-11.7.0-0
      cuda-libraries-dev nvidia/label/cuda-11.7.0/win-64::cuda-libraries-dev-11.7.0-0
      cuda-memcheck      nvidia/label/cuda-11.7.0/win-64::cuda-memcheck-11.7.50-0
      cuda-nsight-compu~ nvidia/label/cuda-11.7.0/win-64::cuda-nsight-compute-11.7.0-0
      cuda-nvcc          nvidia/label/cuda-11.7.0/win-64::cuda-nvcc-11.7.64-0
      cuda-nvdisasm      nvidia/label/cuda-11.7.0/win-64::cuda-nvdisasm-11.7.50-0
      cuda-nvml-dev      nvidia/label/cuda-11.7.0/win-64::cuda-nvml-dev-11.7.50-0
      cuda-nvprof        nvidia/label/cuda-11.7.0/win-64::cuda-nvprof-11.7.50-0
      cuda-nvprune       nvidia/label/cuda-11.7.0/win-64::cuda-nvprune-11.7.50-0
      cuda-nvrtc         nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-11.7.50-0
      cuda-nvrtc-dev     nvidia/label/cuda-11.7.0/win-64::cuda-nvrtc-dev-11.7.50-0
      cuda-nvtx          nvidia/label/cuda-11.7.0/win-64::cuda-nvtx-11.7.50-0
      cuda-nvvp          nvidia/label/cuda-11.7.0/win-64::cuda-nvvp-11.7.50-0
      cuda-runtime       nvidia/label/cuda-11.7.0/win-64::cuda-runtime-11.7.0-0
      cuda-sanitizer-api nvidia/label/cuda-11.7.0/win-64::cuda-sanitizer-api-11.7.50-0
      cuda-toolkit       nvidia/label/cuda-11.7.0/win-64::cuda-toolkit-11.7.0-0
      cuda-tools         nvidia/label/cuda-11.7.0/win-64::cuda-tools-11.7.0-0
      cuda-visual-tools  nvidia/label/cuda-11.7.0/win-64::cuda-visual-tools-11.7.0-0
      git                pkgs/main/win-64::git-2.40.1-haa95532_1
      libcublas          nvidia/label/cuda-11.7.0/win-64::libcublas-11.10.1.25-0
      libcublas-dev      nvidia/label/cuda-11.7.0/win-64::libcublas-dev-11.10.1.25-0
      libcufft           nvidia/label/cuda-11.7.0/win-64::libcufft-10.7.2.50-0
      libcufft-dev       nvidia/label/cuda-11.7.0/win-64::libcufft-dev-10.7.2.50-0
      libcurand          nvidia/label/cuda-11.7.0/win-64::libcurand-10.2.10.50-0
      libcurand-dev      nvidia/label/cuda-11.7.0/win-64::libcurand-dev-10.2.10.50-0
      libcusolver        nvidia/label/cuda-11.7.0/win-64::libcusolver-11.3.5.50-0
      libcusolver-dev    nvidia/label/cuda-11.7.0/win-64::libcusolver-dev-11.3.5.50-0
      libcusparse        nvidia/label/cuda-11.7.0/win-64::libcusparse-11.7.3.50-0
      libcusparse-dev    nvidia/label/cuda-11.7.0/win-64::libcusparse-dev-11.7.3.50-0
      libnpp             nvidia/label/cuda-11.7.0/win-64::libnpp-11.7.3.21-0
      libnpp-dev         nvidia/label/cuda-11.7.0/win-64::libnpp-dev-11.7.3.21-0
      libnvjpeg          nvidia/label/cuda-11.7.0/win-64::libnvjpeg-11.7.2.34-0
      libnvjpeg-dev      nvidia/label/cuda-11.7.0/win-64::libnvjpeg-dev-11.7.2.34-0
      ninja              pkgs/main/win-64::ninja-1.10.2-haa95532_5
      ninja-base         pkgs/main/win-64::ninja-base-1.10.2-h6d14046_5
      nsight-compute     nvidia/label/cuda-11.7.0/win-64::nsight-compute-2022.2.0.13-0
    
    
    
    Downloading and Extracting Packages
    
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    Looking in indexes: https://download.pytorch.org/whl/cu117
    Collecting torch==2.0.1+cu117
      Downloading https://download.pytorch.org/whl/cu117/torch-2.0.1%2Bcu117-cp310-cp310-win_amd64.whl (2343.6 MB)
         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.3 GB 1.6 MB/s eta 0:24:08
    ERROR: Exception:
    Traceback (most recent call last):
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
        yield
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
        data = self._fp_read(amt) if not fp_closed else b""
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
        return self._fp.read(amt) if amt is not None else self._fp.read()
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
        data = self.__fp.read(amt)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\http\client.py", line 466, in read
        s = self.fp.read(amt)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\socket.py", line 705, in readinto
        return self._sock.recv_into(b)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\ssl.py", line 1274, in recv_into
        return self.read(nbytes, buffer)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\ssl.py", line 1130, in read
        return self._sslobj.read(len, buffer)
    TimeoutError: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
        status = run_func(*args)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\cli\req_command.py", line 248, in wrapper
        return func(self, options, args)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
        requirement_set = resolver.resolve(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
        result = self._result = resolver.resolve(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
        state = resolution.resolve(requirements, max_rounds=max_rounds)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
        self._add_to_criteria(self.state.criteria, r, parent=None)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
        if not criterion.candidates:
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
        return bool(self._sequence)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
        return any(self)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
        return (c for c in iterator if id(c) not in self._incompatible_ids)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
        candidate = func()
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
        self._link_candidate_cache[link] = LinkCandidate(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 293, in __init__
        super().__init__(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 156, in __init__
        self.dist = self._prepare()
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 225, in _prepare
        dist = self._prepare_distribution()
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in _prepare_distribution
        return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 538, in prepare_linked_requirement
        return self._prepare_linked_requirement(req, parallel_builds)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 609, in _prepare_linked_requirement
        local_file = unpack_url(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
        file = get_http_url(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
        from_path, content_type = download(link, temp_dir.path)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
        for chunk in chunks:
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
        for chunk in iterable:
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
        for chunk in response.raw.stream(
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
        with self._error_catcher():
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\contextlib.py", line 153, in __exit__
        self.gen.throw(typ, value, traceback)
      File "D:\AI\Oobabooga-NEW\installer_files\env\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
        raise ReadTimeoutError(self._pool, None, "Read timed out.")
    pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.
    Command '"D:\AI\Oobabooga-NEW\installer_files\conda\condabin\conda.bat" activate "D:\AI\Oobabooga-NEW\installer_files\env" >nul && conda install -y -k cuda ninja git -c nvidia/label/cuda-11.7.0 -c nvidia && python -m pip install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117' failed with exit status code '2'. Exiting...
    Press any key to continue . . .

**Comment by ceria117** [comment]
I figured out the issue had to do with pip timing out the download because my drive's read write would pause the download to update my filesystem. For some reason, it was timing out after only 15 seconds of being inactive. I fixed this by changing line 100 in webui.py to: 
`run_cmd('conda install -y -k cuda ninja git -c nvidia/label/cuda-11.7.0 -c nvidia && python -m pip --default-timeout=1200 install torch==2.0.1+cu117 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117', assert_success=True, environment=True)`
The only code I added was `--default-timeout=1200` so that it wouldn't timeout and the download could finish.
