### ISSUE TITLE
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=512

### ISSUE THREAD

**Issue by gemini-mouse** [oobabooga/one-click-installers#44]
Can't find the same issue like this. Kindly help, thank you.

Gradio HTTP request redirected to localhost :)
bin C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "C:\text-generation-webui\one-click-installers-main\text-generation-webui\server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "C:\text-generation-webui\one-click-installers-main\text-generation-webui\modules\training.py", line 13, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\research\__init__.py", line 2, in <module>
    from .autograd._functions import (
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\research\autograd\_functions.py", line 10, in <module>
    from bitsandbytes.autograd._functions import MatmulLtState, GlobalOutlierPooler
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 236, in <module>
    class MatmulLtState:
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 258, in MatmulLtState
    formatB = F.get_special_format_str()
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 283, in get_special_format_str
    major, _minor = torch.cuda.get_device_capability()
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 381, in get_device_capability
    prop = get_device_properties(device)
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "C:\text-generation-webui\one-click-installers-main\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unrecognized CachingAllocator option: max_split_size_mb=512

Using RTX 3060 12G VRAM

**Comment by gemini-mouse** [comment]
Somehow I find the answer, just add the following script in the start_windows.bat

set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:512

**Comment by jogamer777** [comment]
yeah its still relevant
