### ISSUE TITLE
CUDA error and libsbitsandbytes_cpu.so

### ISSUE THREAD

**Issue by Elvis143BRA** [oobabooga/one-click-installers#5]
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "

After trying to load a model, I get this:

Loading alpaca-native-4bit...
CUDA extension not installed.
Loading model ...
Traceback (most recent call last):
  File "D:\oobabooga-windows\text-generation-webui\server.py", line 273, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\oobabooga-windows\text-generation-webui\modules\models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "D:\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 113, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 45, in _load_quant
    model.load_state_dict(torch.load(checkpoint))
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 1116, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 217, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\XXXX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 166, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Press any key to continue . . .

I have 0 programming experience so I don't know how to fix this issue. My PC has an RTX 2060 with 6GB VRAM, 16 GB of RAM, and a Ryzen 5 3600

**Comment by jllllll** [comment]
Try this: https://github.com/oobabooga/text-generation-webui/issues/388#issuecomment-1488998634

It may also simply be a matter of fully deleting the `installer_files` and reinstalling. Make sure you are on the latest version of the installer which can be downloaded from this repo.

**Comment by Elvis143BRA** [comment]
Just want to say that reinstalling everything with this version of the installer (https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda) fixed the problem for me.
