### ISSUE TITLE
Error on 'gallery' load?

### ISSUE THREAD

**Issue by shoggot** [oobabooga/one-click-installers#55]
Via one-click windows installer, post install (which seemed to complete without a hitch), upon running start_windows.bat (or cmd_windows.bat):

```
INFO:Gradio HTTP request redirected to localhost :)
bin C:\Users\shogz\SEA\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading facebook_opt-1.3b...
INFO:Loaded the model in 3.40 seconds.
INFO:Loading the extension "gallery"...
Traceback (most recent call last):
  File "C:\Users\shogz\SEA\oobabooga\text-generation-webui\server.py", line 885, in <module>
    create_interface()
  File "C:\Users\shogz\SEA\oobabooga\text-generation-webui\server.py", line 472, in create_interface
    with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui.chat_css, analytics_enabled=False, title=title, theme=ui.theme) as shared.gradio['interface']:
  File "C:\Users\shogz\SEA\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1285, in __exit__
    self.config = self.get_config_file()
  File "C:\Users\shogz\SEA\oobabooga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1261, in get_config_file
    "input": list(block.input_api_info()),  # type: ignore
  File "C:\Users\shogz\SEA\oobabooga\installer_files\env\lib\site-packages\gradio_client\serializing.py", line 40, in input_api_info
    return (api_info["serialized_input"][0], api_info["serialized_input"][1])
KeyError: 'serialized_input'

Done!
Press any key to continue . . .
```

**Comment by oobabooga** [comment]
Should be fixed now, try updating

**Comment by shoggot** [comment]
Can confirm, worked!
