### ISSUE TITLE
Trying to run one-click-installers start_linux.sh on WSL/Ubuntu error: "Too many levels of symbolic links"

### ISSUE THREAD

**Issue by ksylvan** [oobabooga/one-click-installers#60]
I have a symlink between `~/winhome` and `/mnt/c/Users/kayvan` and the one-click-installers files are in a `src/` subdirectory of that top level directory.

```text
~/winhome/src/one-click-installers$ ./start_linux.sh
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh to /home/kayvan/winhome/src/one-click-installers/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70.9M  100 70.9M    0     0  2128k      0  0:00:34  0:00:34 --:--:-- 3923k
PREFIX=/home/kayvan/winhome/src/one-click-installers/installer_files/conda
Unpacking payload ...

Installing base environment...


Downloading and Extracting Packages


Downloading and Extracting Packages

Preparing transaction: done
Executing transaction: done
installation finished.
Miniconda version:
conda 23.1.0
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.1.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.3.1



## Package Plan ##

  environment location: /home/kayvan/winhome/src/one-click-installers/installer_files/env

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libffi-3.4.4               |       h6a678d5_0         142 KB
    openssl-1.1.1t             |       h7f8727e_0         3.7 MB
    pip-23.0.1                 |  py310h06a4308_0         2.6 MB
    python-3.10.11             |       h7a1cb2a_2        26.8 MB
    setuptools-66.0.0          |  py310h06a4308_0         1.2 MB
    sqlite-3.41.2              |       h5eee18b_0         1.2 MB
    tzdata-2023c               |       h04d1e81_0         116 KB
    wheel-0.38.4               |  py310h06a4308_0          64 KB
    xz-5.4.2                   |       h5eee18b_0         642 KB
    ------------------------------------------------------------
                                           Total:        36.4 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2023.01.10-h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_0
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0
  openssl            pkgs/main/linux-64::openssl-1.1.1t-h7f8727e_0
  pip                pkgs/main/linux-64::pip-23.0.1-py310h06a4308_0
  python             pkgs/main/linux-64::python-3.10.11-h7a1cb2a_2
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0
  setuptools         pkgs/main/linux-64::setuptools-66.0.0-py310h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.41.2-h5eee18b_0
  tk                 pkgs/main/linux-64::tk-8.6.12-h1ccaba5_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  wheel              pkgs/main/linux-64::wheel-0.38.4-py310h06a4308_0
  xz                 pkgs/main/linux-64::xz-5.4.2-h5eee18b_0
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_0



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/notices/core.py", line 109, in wrapper
        return func(*args, **kwargs)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/cli/install.py", line 332, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/cli/install.py", line 361, in handle_txn
        unlink_link_transaction.execute()
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/core/link.py", line 282, in execute
        self.verify()
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/core/link.py", line 243, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/core/link.py", line 637, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/common/io.py", line 547, in map
        yield func(thing)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/core/link.py", line 454, in _verify_individual_level
        error_result = axn.verify()
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/site-packages/conda/core/path_actions.py", line 357, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/home/kayvan/winhome/src/one-click-installers/installer_files/conda/lib/python3.10/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/home/kayvan/winhome/src/one-click-installers/installer_files/conda/pkgs/ncurses-6.4-h6a678d5_0/share/terminfo/n/ncr260vt300wpp'

`$ /home/kayvan/winhome/src/one-click-installers/installer_files/conda/bin/conda create -y -k --prefix /home/kayvan/winhome/src/one-click-installers/installer_files/env python=3.10`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/kayvan/winhome/src/one-click-installers/installer_files/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game
                          s:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program
                          Files/PowerShell/7:/mnt/c/Program Files/NVIDIA GPU Computing
                          Toolkit/CUDA/v12.1/bin:/mnt/c/Program Files/NVIDIA GPU Computing Toolk
                          it/CUDA/v12.1/libnvvp:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Wi
                          ndows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/m
                          nt/c/Windows/System32/OpenSSH/:/mnt/c/Program
                          Files/PowerShell/7/:/mnt/c/Program Files/Rancher
                          Desktop/resources/resources/win32/bin/:/mnt/c/Program Files/Rancher
                          Desktop/resources/resources/linux/bin/:/mnt/c/Program Files/GitHub
                          CLI/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/NVIDIA
                          Corporation/Nsight Compute 2023.1.1/:/mnt/c/Program Files (x86)/NVIDIA
                          Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/Users/kayvan/scoop/shims:/mnt/c/User
                          s/kayvan/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/kayvan/AppDa
                          ta/Local/Programs/Microsoft VS Code/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/kayvan/.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __glibc=2.35=0
                          __linux=5.15.90.1=0
                          __unix=0=0
       base environment : /home/kayvan/winhome/src/one-click-installers/installer_files/conda  (writable)
      conda av data dir : /home/kayvan/winhome/src/one-click-installers/installer_files/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kayvan/winhome/src/one-click-installers/installer_files/conda/pkgs
                          /home/kayvan/.conda/pkgs
       envs directories : /home/kayvan/winhome/src/one-click-installers/installer_files/conda/envs
                          /home/kayvan/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Linux/5.15.90.1-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
Conda environment is empty.
```

**Comment by jllllll** [comment]
It's not the most ideal solution, but you should be able to use `--copy` to get around this:

Change line 43 of `start_linux.sh` to:
```
"$CONDA_ROOT_PREFIX/bin/conda" create --copy -y -k --prefix "$INSTALL_ENV_DIR" python=3.10
```
Change line 63 of `webui.py` to:
```
run_cmd("conda install --copy -y -k pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git -c pytorch -c nvidia/label/cuda-11.7.0 -c nvidia", assert_success=True, environment=True)
```
You can make a similar change to line 68 if cpu-only.

**Comment by ksylvan** [comment]
Thanks. I understand. We can close this.

I got around the problem by starting from scratch in the WSL container, and just copying the models I use in from the Windows filesystem. By the way, the one-click installers are fantastic! Thank you!
