### ISSUE TITLE
Fresh install on Windows not working

### ISSUE THREAD

**Issue by aaron777collins** [oobabooga/one-click-installers#73]
Error while running start_windows.bat as a fresh install:
```bash
Traceback (most recent call last):
  File "D:\repos\one-click-installers\text-generation-webui\server.py", line 1087, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\repos\one-click-installers\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "D:\repos\one-click-installers\text-generation-webui\modules\models.py", line 263, in llamacpp_loader
    from modules.llamacpp_model import LlamaCppModel
  File "D:\repos\one-click-installers\text-generation-webui\modules\llamacpp_model.py", line 11, in <module>
    from llama_cpp import Llama, LlamaCache
  File "D:\repos\one-click-installers\installer_files\env\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "D:\repos\one-click-installers\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 73, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "D:\repos\one-click-installers\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 52, in _load_shared_library
    os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
  File "D:\repos\one-click-installers\installer_files\env\lib\os.py", line 1118, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\repos\\one-click-installers\\installer_files\\env\\bin'
```

Not sure why it's referencing bin while on windows? Anyone know a quick fix?

**Comment by aaron777collins** [comment]
I'm thinking I may have accidentally started the CUDA install then tried the CPU install. I am re-trying the install from a proper fresh install and I will close this if it fixes it.

**Comment by aaron777collins** [comment]
I added the --cpu flag. Not sure why it's still using CUDA? Still looking for a fix :)

**Comment by jllllll** [comment]
https://github.com/oobabooga/text-generation-webui/issues/2417#issuecomment-1567459548
